function data = Rocket_5()

reactants =   [                                           ...
             CEA.Reactant('C3H8',                            ...
                     'Type','Fuel',                     ...
                     'E',DimVar(-10000,'J/mol'),        ...
                     'T',DimVar(298,'K'),               ...         
                     'Q',DimVar(1,'kg'))                ...
            CEA.Reactant('H2O2(L)',                          ...
                    'Type','ox',                        ...
                    'T',DimVar(298,'K'),                ...         
                    'Q',DimVar(0.9,'kg'))               ...
            CEA.Reactant('H2O(L)',                           ...
                    'Type','ox',                        ...
                    'T',DimVar(298,'K'),                ...         
                    'Q',DimVar(0.1,'kg'))               ...
            ];     
        

data =  CEA.Run(reactants,                                ...
        'ProblemType','Rocket',                         ...
        'Flow','eq',                                    ...
        'CombLength','fac',                             ...
        'CR','5',                                       ...
        'Pc',DimVar(1,'bar'),                           ...
        'OF',1,                                         ...
        'Outputs',{'t'});
