function data = Rocket_2()

reactants =   [                                           ...
             CEA.Reactant('H2(L)',                           ...
                     'Type','Fuel',                     ...
                     'T',DimVar(20.27,'K'),             ...         
                     'Q',DimVar(1,'kg'))                ...
            CEA.Reactant('O2(L)',                            ...
                    'Type','ox',                        ...
                    'T',DimVar(90.17,'K'),              ...         
                    'Q',DimVar(1,'kg'))                 ...
            ];     
        

data =  CEA.Run(reactants,                                ...
        'ProblemType','Rocket',                         ...
        'Flow','eq',                                    ...
        'Pc',DimVar(1,'bar'),                           ...
        'OF',1,                                         ...
        'Outputs',{'isp'});
